services:
  - type: web
    name: mini-games-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: SPONSOR_CHANNELS
        value: ""
      - key: COIN_TO_INR
        value: "0.01"
      - key: MIN_REDEEM_COINS
        value: "5000"
      - key: PYTHON_VERSION
        value: "3.11.9"
